## References:
## ----------
##
##  1. Docker Compose example for Simple Monitor: https://github.com/camunda-community-hub/zeebe-docker-compose/blob/master/simple-monitor/docker-compose.yml
##  2. Zeebe with Hazelcast exporter image: https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/pkgs/container/zeebe-with-hazelcast-exporter
##  3. Camunda Zeebe Docker images: https://hub.docker.com/r/camunda/zeebe/tags
##  4. Simple Monitor Docker images: https://github.com/camunda-community-hub/zeebe-simple-monitor/pkgs/container/zeebe-simple-monitor
##  5. Camunda Platform 8 Docs, Zeebe, Docker: https://docs.camunda.io/docs/1.0/components/zeebe/deployment-guide/docker/install/
##  6. Camunda Platform 8, Docker Compose: https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml
##  7. Camunda Platform 8, Docker Compose (core): https://github.com/camunda/camunda-platform/blob/main/docker-compose-core.yaml
##  8. Task List, Docker images: https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#tasklist
##  9. Task List, configuration: https://docs.camunda.io/docs/self-managed/tasklist-deployment/configuration/
##

version: '3.7'

services:
  zeebe:
    container_name: zeebe
#    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.2.0
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter@sha256:f05c53ccede0a47161eb863057c87dd2143764525e18913ab2354b82375619b0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    ports:
      - "26500:26500"
      - "5701:5701"
      - "9600:9600"
    volumes:
      - zeebe-data:/usr/local/zeebe/data

  monitor:
    container_name: monitor
#    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor@sha256:99ae10ed57b086dc898b348500ef87debe724904a49671bebf02569110b3a8e0
    environment:
      - zeebe.client.broker.gatewayAddress=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe

  db:
    build:
      context: ./postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  zeebe-data:
  postgres-data: